<?php

namespace App\Models;

use CodeIgniter\Model;

class SysmondModel extends Model
{
    protected $table = 'sysmond'; // Tablo adı

    // Birincil anahtar (primary key) sütunu
    protected $primaryKey = 'id';

    // Otomatik artan (auto-increment) birincil anahtar kullanılıyorsa, bu ayarı yapabilirsin.
    protected $useAutoIncrement = true;

    // Tabloya eklenebilir sütunlar (insert işlemi için)
    protected $allowedFields = [
        'COMPANYID','CHANGE_LOG', 'STOCKID', 'STOCKTYPENAME', 'STOCKTYPE', 'STOCKNO', 'STOCKNAME',
        'GROUPCODE', 'SEASON', 'BRAND', 'MODEL', 'SPECCODE1', 'SPECCODE2',
        'EMPLOYEENO', 'EMPLOYEENAME', 'EMPLOYEETYPE', 'EMPLOYEEID', 'STATUSNAME',
        'STATUS', 'NOTEID', 'CANCELDATE', 'DESCRIPTION', 'DEBIT', 'CREDIT',
        'REMTOTAL', 'REMTYPENAME', 'REMTYPE', 'CURRCODE', 'CURRDEBIT', 'CURRCREDIT',
        'CURRREMTOTAL', 'CURRREMTYPENAME', 'CURRREMTYPE', 'QENTRY', 'QEXIT', 'QREM',
        'QREM2', 'QREM3', 'QRESERVE', 'QRESERVE2', 'QRESERVE3', 'QDEPOT', 'QREMNOTGRADE',
        'STOCKNAME2', 'DEPOTNO', 'DEPOTNAME', 'DEPOTTYPE', 'DEPOTID', 'STOREHOUSEID',
        'UNITNAME', 'UNITIDNAME', 'INTUNITCODE', 'UNITID', 'SPECCODE3', 'SPECCODE4',
        'SPECCODE5', 'SPECCODE6', 'SPECCODE7', 'SPECCODE8', 'SPECCODE9', 'SPECCODE10',
        'PARENTID', 'TOUR', 'DECITEKS', 'LASTPURCPRICE', 'LASTPURCDATE', 'LASTPURCCURRPRICE',
        'VATSALES', 'VATPURCHASE', 'QUANTITYMIN', 'QUANTITYMAX', 'MINORDERQUANTITY', 'TAXPRIVATE',
        'TAXPRIVATETOTAL', 'ORDERSLEVEL', 'ACTNOCUSTOMER', 'ACTNAMECUSTOMER', 'ACTIDCUSTOMER',
        'ACTNOSUPPLIER', 'ACTNAMESUPPLIER', 'ACTIDSUPPLIER', 'PACKAGEQUANTITY', 'CUSTOMERSTOCKNO',
        'SUPPLIERSTOCKNO', 'FOLLOWLOT', 'FOLLOWSTOCK', 'FOLLOWSERIAL', 'FOLLOWSERIALFREE',
        'FOLLOWSTOREHOUSE', 'DYNAMICPLACE', 'MATRIX', 'STOCKSERISTART', 'WARRANTY', 'WARRANTYTYPENAME',
        'WARRANTYTYPE', 'FORMULAID', 'PROVIDEDURATION', 'PROVIDEDURATIONTYPENAME', 'PROVIDEDURATIONTYPE',
        'PRICELIST', 'BARCODEDIV', 'PACKAGENAME', 'STOCKPACKAGEID', 'CHANGERECORD', 'POSDEPARTMAN',
        'POSDEPARTMANT', 'POSPLU', 'POSUNITID', 'POSTARTILI', 'ACCGROUPCODE', 'TREXMODULSID',
        'QTYSELECT', 'NOTCONVERTUNIT', 'STOCKPRICETYPEID', 'PSTOCKPRICETYPEID', 'EDUCATIONTIME',
        'GTYPENO', 'GTYPENAME', 'GTYPEID', 'MATRIXID', 'MATRIXID2', 'MATRIXID3', 'MATRIXSTOCKID',
        'SCURREXCTYPENAME', 'SCURREXCTYPE', 'PCURREXCTYPENAME', 'PCURREXCTYPE', 'MATRIXUNIQID',
        'MATRIXUNIQID2', 'MATRIXUNIQID3', 'ADVRATE', 'ADVROTATE', 'RELATIONSTOCKNO',
        'RELATIONSTOCKNAME', 'STOCKIDRELATION', 'TEKSSTOCK', 'SHELFLIFE', 'SHELFLIFETYPENAME',
        'SHELFLIFETYPE', 'LEGALLIABILITY', 'STOCKPOINT', 'DEVIATIONDATE', 'FOLLOWBARCODE', 'MSG',
        'MINREQQUANTITY', 'NOBONUS', 'CONVERTQTY', 'SPECIFICGRAVITY', 'WEBSTOCK', 'PSSAMPLELEVELID',
        'MRPLOSSPERCENT', 'DCASPLANCALCOEE', 'STOCKMINPRICE', 'TRANSCODE', 'MANUFACTUREPRICE',
        'MANUFACTURECURR', 'MANUFACTUREDATE', 'ORIGIN', 'CLASSIFICATIONCODE', 'LABELNO', 'QTYTREE',
        'DMOPRODUCTNO', 'DMOGLBPRODUCTNO', 'PRICEEDITDATE', 'INSERTUSERID', 'INSERTDATE', 'EDITUSERID',
        'EDITDATE', 'GLBALERTID', 'NOTES'
    ];

    // Tablodaki tarih alanlarını otomatik yönetme (created_at, updated_at)
    protected $useTimestamps = true;
    protected $createdField  = 'INSERTDATE';
    protected $updatedField  = 'EDITDATE';

    // Tarihler için format
    protected $dateFormat = 'datetime';

    // İsteğe bağlı doğrulama kuralları ekleyebilirsin
    protected $validationRules = [];
    protected $validationMessages = [];
    protected $skipValidation = false;
}